
pipeline {

    agent

    stages {
        stage('Build') {
            steps {
                sh 'make' 
                archiveArtifacts artifacts: ' docker-compose up -d', fingerprint: true 
            }
        }
    }

    stage('Test') {
        steps {
            echo 'Testing..'
        }

    stages {
        stage('Deploy') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
            steps {
                sh 'make publish'
            }




}
    